INSERT INTO MEMBERS(MEMBER_ID, CITY, STREET, ZIPCODE, NAME) VALUES(1, '서울', '길음로 92', '930-33', '이봉수');
--INSERT INTO MEMBERS(MEMBER_ID, CITY, STREET, ZIPCODE, NAME) VALUES(2, '경기', '덕장로 22', '910-172', '조원진');

